# Note: builds configured with this file will use the Travis CI default infrastructure (Ubuntu Xenial 16.04).

language: python
python: "3.7"  # maps to 3.7.1

addons:
  postgresql: "10"

env:
  - DJANGO_DEBUG=True DJANGO_SECRET_KEY=djangosecretkey DJANGO_ALLOWED_HOSTS=127.0.0.1 DATABASE_URL=postgres://travis_django:travis_password@127.0.0.1:5432/travis_database

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE USER travis_django WITH PASSWORD 'travis_password';" -U postgres
  - psql -c "ALTER USER travis_django CREATEDB;" -U postgres  # allows Django to create a test database
  - psql -c "CREATE DATABASE travis_database OWNER travis_django;" -U postgres
  - python manage.py migrate
  - python manage.py collectstatic

# command to run tests
script:
  - python manage.py test
