# Note: builds configured with this file will use the Travis CI default infrastructure (Ubuntu Xenial 16.04).

language: python
python: "3.7"  # maps to 3.7.1

addons:
  postgresql: "10"

env:
  - DJANGO_SECRET_KEY=djangosecretkey DJANGO_DB_ENGINE=django.db.backends.postgresql DJANGO_DB_NAME=travis_database DJANGO_DB_USER=travis_django DJANGO_DB_PASSWORD=travis_password DJANGO_DB_HOST=127.0.0.1 DJANGO_DB_PORT=5432

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE USER travis_django WITH PASSWORD 'travis_password';" -U postgres
  - psql -c "ALTER USER travis_django CREATEDB;" -U postgres  # allows Django to create a test database
  - psql -c "CREATE DATABASE travis_database OWNER travis_django;" -U postgres
  - python manage.py migrate

# command to run tests
script:
  - python manage.py test
