# Note: builds configured with this file will use the Travis CI default infrastructure (Ubuntu Xenial 16.04).
language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python --version