# Note: builds configured with this file will use the Travis CI default infrastructure (Ubuntu Xenial 16.04).

language: python
python: "3.7"  # maps to 3.7.1

services: postgresql

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to run tests
script:
  - psql --version
  - psql -c 'show server_version;' -U postgres