# Note: builds configured with this file will use the Travis CI default infrastructure (Ubuntu Xenial 16.04).

language: python
python: "3.7"  # maps to 3.7.1

addons:
  postgresql: "10"

env:
  - DJANGO_SECRET_KEY=djangosecretkey DJANGO_DB_ENGINE=django.db.backends.postgresql DJANGO_DB_NAME=travis_database DJANGO_DB_USER=travis DJANGO_DB_PASSWORD=travis_password DJANGO_DB_HOST=127.0.0.1 DJANGO_DB_PORT=5432

# command to install dependencies
install:
  - pip install -r requirements.txt

before_script:
  - psql --version
  - psql -c "SHOW server_version;" -U postgres
  - psql -c "CREATE USER travis WITH PASSWORD 'travis_password';" -U postgres
  - psql -c "ALTER USER travis CREATEDB;" -U postgres  # allows Django to create a test database
  - psql -c "CREATE DATABASE travis_database OWNER travis;" -U postgres
  - python manage.py migrate

# command to run tests
script:
  - python manage.py shell --command="from catalog.models import Genre; Genre.objects.all(); g = Genre(name=\"Comedy\"); g.save(); Genre.objects.all()"
